name: hello world
on: push       
jobs:
  actions-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: print index.html
        run: cat index.html
  
