name: hello world
on: 
  push:
    branches:
      - main
      - develop
      - 'releses/**'

  pull_request:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build an App
        run: echo "Build an Application"
  