name: Env_Var
on: push 
env:
  ENV_VARB: dev
    
      
jobs:
  EnvirmntVARB:
    runs-on: ubuntu-latest
    steps:
      - name: creating envirement-varb
        run: echo "app is connecting to $ENV_VARB"
  