name: INPUT-DEMO
on:
  workflow_dispatch:
    inputs:
      environment:
        desprition: 'choose the option to deploy'
        required: true
        default: 'dev'
        options:
          - dev
          - test
          - prod

  jobs:
    input-demo:
      runs-on: ubuntu-latest
      steps:
        -name: "Deploy the app"
          run: echo :Deploying the app to ${{inputs.environment}}