name: Input_Demo
on:
  workflow_dispatch
    input:
      environment:
        description: choose the environment option
        required: true
        default: dev
  jobs:
    input-demo:
      runs-on: ubuntu-latest
      steps:
        - name: Deploy an app
          run: echo "deploying the app ${{inputs.environment}}"
    



