name: INPUT-DEMO
on:
  workflow_dispatch:
    inputs:
      environment:
        description: choose the environment option
        required: true
        default: 'dev'
        typs: choice
        options:
          - dev
          - test
          - prod

  jobs:
    input-demo:
      runs-on: ubuntu-latest
      steps:
        - name: Deploying an APP
          run: echo "Deploying the app to ${{inputs.environment}}"